import type { FeaturedProduct, Product } from "@/types";

export const FEATURED_PRODUCTS_MOCK: FeaturedProduct[] = [
    {
        id: "72",
        name: "Crema de Leche",
        imageUrl: "/images/products/crema-de-leche/35/crema-de-leche-35-1.webp",
        presentationName: "35% Grasa"
    },
    {
        id: "46",
        name: "Yogurt Batido",
        imageUrl: "/images/products/yogurt/batido/fresa/yogurt-batido-fresa-1.webp",
        presentationName: "Fresa"
    },
    {
        id: "14",
        name: "Queso de Corte",
        imageUrl: "/images/products/queso/de-corte/500gr/queso-de-corte-500gr-1.webp",
        presentationName: "500 gr"
    },
    {
        id: "70",
        name: "Leche Fresca",
        imageUrl: "/images/products/leche/fresca/pasteurizada/1lt/leche-fresca-pasteurizada-1lt-1.webp",
        presentationName: "Pasteurizada"
    },
    {
        id: "68",
        name: "Mantequilla",
        imageUrl: "/images/products/mantequilla/500gr/mantequilla-500gr-1.webp",
        presentationName: "500 gr"
    }
]

export const PRODUCTS_MOCK: Product[] = [
    {
        id: "1",
        name: "Queso Suizo",
        meditionUnit: "3.5 kg",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Suizo de 3.5kg",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "2",
        name: "Queso Suizo",
        meditionUnit: "1 kg",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Suizo de 1kg",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "3",
        name: "Queso Suizo",
        meditionUnit: "500 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Suizo de 500gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "4",
        name: "Queso Suizo",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Suizo de 250gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "5",
        name: "Queso Suizo Laminado",
        meditionUnit: "500 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Suizo Laminado de 500gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "6",
        name: "Queso Suizo Laminado",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Suizo Laminado de 250gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "7",
        name: "Queso Suizo con Orégano",
        meditionUnit: "3.5 kg",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Suizo con Orégano de 3.5kg",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "8",
        name: "Queso Suizo con Orégano",
        meditionUnit: "1 kg",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Suizo con Orégano de 1kg",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "9",
        name: "Queso Suizo con Orégano",
        meditionUnit: "500 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Suizo con Orégano de 500gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "10",
        name: "Queso Suizo con Orégano",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Suizo con Orégano de 250gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "11",
        name: "Queso Suizo con Orégano Redondo",
        meditionUnit: "500 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Suizo con Orégano Redondo de 500gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "12",
        name: "Queso de Corte",
        meditionUnit: "3.5 kg",
        imagesUrls: [""],
        specifications: [],
        description: "Queso de Corte de 3.5kg",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "13",
        name: "Queso de Corte",
        meditionUnit: "1 kg",
        imagesUrls: [""],
        specifications: [],
        description: "Queso de Corte de 1kg",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "14",
        name: "Queso de Corte",
        meditionUnit: "500 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso de Corte de 500gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "15",
        name: "Queso de Corte",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso de Corte de 250gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "16",
        name: "Queso Fresco",
        meditionUnit: "3.5 kg",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Fresco de 3.5kg",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "17",
        name: "Queso Fresco",
        meditionUnit: "1 kg",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Fresco de 1kg",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "18",
        name: "Queso Fresco",
        meditionUnit: "500 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Fresco de 500gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "19",
        name: "Queso Fresco",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Fresco de 250gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "20",
        name: "Queso Dambo",
        meditionUnit: "3.5 kg",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Dambo de 3.5kg",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "21",
        name: "Queso Dambo",
        meditionUnit: "1 kg",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Dambo de 1kg",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "22",
        name: "Queso Dambo",
        meditionUnit: "500 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Dambo de 500gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "23",
        name: "Queso Dambo",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Dambo de 250gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "24",
        name: "Queso Dambo Laminado",
        meditionUnit: "500 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Dambo Laminado de 500gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "25",
        name: "Queso Dambo Laminado",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Dambo Laminado de 250gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "26",
        name: "Queso Mantecoso",
        meditionUnit: "1 kg",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Mantecoso de 1kg",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "27",
        name: "Queso Mantecoso",
        meditionUnit: "500 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Mantecoso de 500gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "28",
        name: "Queso Mantecoso",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Mantecoso de 250gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "29",
        name: "Queso Edam",
        meditionUnit: "3.5 kg",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Edam de 3.5kg",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "30",
        name: "Queso Edam Laminado",
        meditionUnit: "500 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Edam Laminado de 500gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "31",
        name: "Queso Edam Laminado",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Edam Laminado de 250gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "32",
        name: "Queso Parmesano Para Rallar",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Parmesano Para Rallar de 250gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "33",
        name: "Queso Parmesano Rallado",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Parmesano Rallado de 250gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "34",
        name: "Queso Mozzarella con Sal 2 kg",
        meditionUnit: "2 kg",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Mozzarella con Sal de 2 kg",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "35",
        name: "Queso Mozzarella Paquete 5 kg",
        meditionUnit: "5 kg",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Mozzarella Paquete de 5 kg",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "36",
        name: "Queso Mozzarella sin Sal 250 gr",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Mozzarella sin Sal de 250 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "37",
        name: "Quesillo 800 gr",
        meditionUnit: "800 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Quesillo de 800 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "38",
        name: "Queso Paria 800 gr",
        meditionUnit: "800 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Paria de 800 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "39",
        name: "Queso Ricotta 250 gr",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Ricotta de 250 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "40",
        name: "Queso Ricotta 500 gr",
        meditionUnit: "500 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Queso Ricotta de 500 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "41",
        name: "Yogurt Batido",
        presentationName: "Natural",
        meditionUnit: "950 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Batido Natural de 950 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "42",
        name: "Yogurt Batido",
        presentationName: "Natural sin azúcar",
        meditionUnit: "950 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Batido Natural sin azúcar de 950 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "43",
        name: "Yogurt Batido",
        presentationName: "Piña",
        meditionUnit: "950 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Batido Piña de 950 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "44",
        name: "Yogurt Batido",
        presentationName: "Vainilla",
        meditionUnit: "950 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Batido Vainilla de 950 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "45",
        name: "Yogurt Batido",
        presentationName: "Lúcuma",
        meditionUnit: "950 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Batido Lúcuma de 950 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "46",
        name: "Yogurt Batido",
        presentationName: "Fresa",
        meditionUnit: "950 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Batido Fresa de 950 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "47",
        name: "Yogurt Batido",
        presentationName: "Durazno",
        meditionUnit: "950 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Batido Durazno de 950 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "48",
        name: "Yogurt Batido",
        presentationName: "Higo",
        meditionUnit: "950 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Batido Higo de 950 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "49",
        name: "Yogurt Batido",
        presentationName: "Guanábana",
        meditionUnit: "950 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Batido Guanábana de 950 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "50",
        name: "Yogurt Frutado",
        presentationName: "Higo",
        meditionUnit: "900 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Frutado Higo de 900 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "51",
        name: "Yogurt Frutado",
        presentationName: "Higo",
        meditionUnit: "450 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Frutado Higo de 450 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "52",
        name: "Yogurt Frutado Cuchareable",
        presentationName: "Higo",
        meditionUnit: "200 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Frutado Cuchareable Higo de 200 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "53",
        name: "Yogurt Frutado",
        presentationName: "Mango",
        meditionUnit: "900 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Frutado Mango de 900 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "54",
        name: "Yogurt Frutado",
        presentationName: "Mango",
        meditionUnit: "450 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Frutado Mango de 450 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "55",
        name: "Yogurt Frutado Cuchareable",
        presentationName: "Mango",
        meditionUnit: "200 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Frutado Cuchareable Mango de 200 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "56",
        name: "Yogurt Frutado",
        presentationName: "Arándano",
        meditionUnit: "900 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Frutado Arándano de 900 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "57",
        name: "Yogurt Frutado",
        presentationName: "Arándano",
        meditionUnit: "450 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Frutado Arándano de 450 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "58",
        name: "Yogurt Frutado Cuchareable",
        presentationName: "Arándano",
        meditionUnit: "200 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Frutado Cuchareable Arándano de 200 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "59",
        name: "Yogurt Frutado",
        presentationName: "Fresa",
        meditionUnit: "900 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Frutado Fresa de 900 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "60",
        name: "Yogurt Frutado",
        presentationName: "Fresa",
        meditionUnit: "450 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Frutado Fresa de 450 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "61",
        name: "Yogurt Frutado Cuchareable",
        presentationName: "Fresa",
        meditionUnit: "200 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Frutado Cuchareable Fresa de 200 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "62",
        name: "Yogurt Griego",
        presentationName: "Natural",
        meditionUnit: "1 kg",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Griego Natural de 1 kg",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "63",
        name: "Yogurt Griego",
        presentationName: "Natural",
        meditionUnit: "500 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Griego Natural de 500 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "64",
        name: "Yogurt Griego",
        presentationName: "Natural",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Griego Natural de 250 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "65",
        name: "Yogurt Griego",
        presentationName: "Fresa",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Griego Fresa de 250 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "66",
        name: "Yogurt Griego",
        presentationName: "Arándano",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Griego Arándano de 250 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "67",
        name: "Yogurt Griego",
        presentationName: "Aguaymanto",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Yogurt Griego Aguaymanto de 250 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "68",
        name: "Mantequilla",
        meditionUnit: "500 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Mantequilla de 500 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "69",
        name: "Mantequilla",
        meditionUnit: "250 gr",
        imagesUrls: [""],
        specifications: [],
        description: "Mantequilla de 250 gr",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "70",
        name: "Leche Fresca",
        presentationName: "Pasteurizada",
        meditionUnit: "1 litro",
        imagesUrls: [""],
        specifications: [],
        description: "Leche Fresca Pasteurizada de 1 litro",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "71",
        name: "Crema de Leche",
        presentationName: "50% Grasa",
        meditionUnit: "1 litro",
        imagesUrls: [""],
        specifications: [],
        description: "Crema de Leche 50% Grasa de 1 litro",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    },
    {
        id: "72",
        name: "Crema de Leche",
        presentationName: "35% Grasa",
        meditionUnit: "1 litro",
        imagesUrls: [""],
        specifications: [],
        description: "Crema de Leche 35% Grasa de 1 litro",
        featuresDetails: "",
        uses: [],
        relatedProducts: []
    }
];